# Generated by Django 5.1 on 2024-09-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_detalleventa_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio',
        ),
    ]
